### ISSUE TITLE
cssa is not a function

### ISSUE THREAD

**Issue by craigcosmo** [iamvdo/pleeease-filters#14]
I tried this and got error.
```
.shadow{
	-webkit-filter: drop-shadow( 3px 3px 2px rgba(0,0,0,.7) );
	filter: drop-shadow( 3px 3px 2px rgba(0,0,0,.7) ); 
}
```

stacktrace
```
 ERROR in ./~/css-loader?sourceMap&importLoaders=1!./~/postcss-loader?sourceMap&parser=postcss-scss!./app/style/page.css
    Module build failed: TypeError: oneColor(...).cssa is not a function
        at Object.Filter.filters.dropShadow (/Users/craigcosmo/Desktop/lark chat app/node_modules/pleeease-filters/index.js:401:36)
        at Filter.convert (/Users/craigcosmo/Desktop/lark chat app/node_modules/pleeease-filters/index.js:543:30)
        at /Users/craigcosmo/Desktop/lark chat app/node_modules/pleeease-filters/index.js:575:36
        at /lib/container.es6:152:28
        at /lib/container.es6:110:26
        at Rule.each (/lib/container.es6:78:22)
        at Rule.walk (/lib/container.es6:109:21)
        at Rule.walkDecls (/lib/container.es6:150:25)
        at /Users/craigcosmo/Desktop/lark chat app/node_modules/pleeease-filters/index.js:556:8
        at /lib/container.es6:199:28
        at /lib/container.es6:110:26
        at Root.each (/lib/container.es6:78:22)
        at Root.walk (/lib/container.es6:109:21)
        at Root.walkRules (/lib/container.es6:197:25)
        at Filter.postcss (/Users/craigcosmo/Desktop/lark chat app/node_modules/pleeease-filters/index.js:554:6)
        at LazyResult.run (/lib/lazy-result.es6:321:20)
        at /lib/lazy-result.es6:248:32
        at LazyResult.asyncTick (/lib/lazy-result.es6:246:13)
        at /lib/lazy-result.es6:260:22
        at LazyResult.asyncTick (/lib/lazy-result.es6:246:13)
        at /lib/lazy-result.es6:260:22
        at LazyResult.asyncTick (/lib/lazy-result.es6:246:13)
```

**Comment by iamvdo** [comment]
Fixed in 3.0.1. Thanks.
